<?xml version="1.0" encoding="UTF-8"?><record_update table="sys_ui_message">
    <sys_ui_message action="INSERT_OR_UPDATE">
        <application/>
        <code/>
        <commented_message/>
        <key>property_api_err</key>
        <language>en</language>
        <message>The {0} has encountered the following error: {1}</message>
        <sys_class_name>sys_ui_message</sys_class_name>
        <sys_created_by>andrew.barnes@snc</sys_created_by>
        <sys_created_on>2022-08-01 15:53:18</sys_created_on>
        <sys_id>df0fc769c249d1508950f90564017093</sys_id>
        <sys_mod_count>0</sys_mod_count>
        <sys_name>property_api_err</sys_name>
        <sys_package display_value="pwerawer" source="x_snc_pwerawer">970fc769a949d150ed447ecd937884e8</sys_package>
        <sys_policy/>
        <sys_scope display_value="pwerawer">970fc769a949d150ed447ecd937884e8</sys_scope>
        <sys_update_name>sys_ui_message_df0fc769c249d1508950f90564017093</sys_update_name>
        <sys_updated_by>andrew.barnes@snc</sys_updated_by>
        <sys_updated_on>2022-08-01 15:53:18</sys_updated_on>
    </sys_ui_message>
</record_update>
